In [40]:
import pandas as pd

orders = pd.read_csv(r"C:\Users\Sam\Desktop\retail-ai-project\orders.csv")
orders.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [41]:
orders.shape

(9994, 16)

In [42]:
orders.columns.tolist()

['Order Id',
 'Order Date',
 'Ship Mode',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Category',
 'Sub Category',
 'Product Id',
 'cost price',
 'List Price',
 'Quantity',
 'Discount Percent']

In [43]:
orders.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [44]:
orders.dtypes

Order Id             int64
Order Date          object
Ship Mode           object
Segment             object
Country             object
City                object
State               object
Postal Code          int64
Region              object
Category            object
Sub Category        object
Product Id          object
cost price           int64
List Price           int64
Quantity             int64
Discount Percent     int64
dtype: object

In [45]:
orders.columns = orders.columns.str.lower().str.replace(" ", "_")
print("Cleaned columns:", orders.columns.tolist())

Cleaned columns: ['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'category', 'sub_category', 'product_id', 'cost_price', 'list_price', 'quantity', 'discount_percent']

In [46]:
orders.dropna(inplace=True)

In [47]:
orders.drop(columns=["product_id"],axis=1)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,210,240,2,3

In [48]:
orders["orders_date"] = pd.to_datetime(orders["order_date"])

In [52]:
#orders.drop(columns=["order_date"],axis=1)

In [60]:
orders['order_month'] = orders['orders_date'].dt.month
orders["order_year"]= orders["orders_date"].dt.year
orders['order_quarter'] = orders['orders_date'].dt.quarter

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,orders_date,order_month
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,2023-03-01,3
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,2023-08-15,8
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,2023-01-10,1
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,2022-06-18,6
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,2022-07-13,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,2023-02-18,2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,2023-03-17,3
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,2022-08-07,8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,2022-11-19,11
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,2022-07-17,7

In [61]:
orders['discount']= orders['list_price'] * orders ['discount_percent']/100

In [62]:
orders

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,...,product_id,cost_price,list_price,quantity,discount_percent,orders_date,order_month,order_year,order_quarter,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,...,FUR-BO-10001798,240,260,2,2,2023-03-01,3,2023,1,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,...,FUR-CH-10000454,600,730,3,3,2023-08-15,8,2023,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,...,OFF-LA-10000240,10,10,2,5,2023-01-10,1,2023,1,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,...,FUR-TA-10000577,780,960,5,2,2022-06-18,6,2022,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,...,OFF-ST-10000760,20,20,2,5,2022-07-13,7,2022,3,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,...,FUR-FU-10001889,30,30,3,4,2023-02-18,2,2023,1,1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,...,FUR-FU-10000747,70,90,2,4,2023-03-17,3,2023,1,3.6
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,...,TEC-PH-10003645,220,260,2,2,2022-08-07,8,2022,3,5.2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,...,OFF-PA-10004041,30,30,4,3,2022-11-19,11,2022,4,0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,...,OFF-AP-10002684,210,240,2,3,2022-07-17,7,2022,3,7.2

In [63]:
orders['discount'] = orders['list_price'] * orders['discount_percent'] / 100
orders['sale_price'] = orders['list_price'] - orders['discount']
orders['profit'] = orders['sale_price'] - orders['cost_price']
orders['revenue'] = orders['sale_price'] * orders['quantity']
orders['profit_margin'] = (orders['profit'] / orders['sale_price'] * 100).round(2)

# Quick check
print("New columns added:")
print(orders[['order_date', 'order_month', 'order_year', 
              'order_quarter', 'sale_price', 'revenue', 
              'profit', 'profit_margin']].head())
print("\nShape:", orders.shape)

New columns added:
   order_date  order_month  order_year  order_quarter  sale_price  revenue  \
0  2023-03-01            3        2023              1       254.8    509.6
1  2023-08-15            8        2023              3       708.1   2124.3
2  2023-01-10            1        2023              1         9.5     19.0
3  2022-06-18            6        2022              2       940.8   4704.0
4  2022-07-13            7        2022              3        19.0     38.0

   profit  profit_margin
0    14.8           5.81
1   108.1          15.27
2    -0.5          -5.26
3   160.8          17.09
4    -1.0          -5.26

Shape: (9993, 25)

In [66]:
from sqlalchemy import create_engine

print("loading into datbase....")
engine = create_engine('sqlite:///retail.db')

loading into datbase....

In [67]:
orders.to_sql("orders",engine,if_exists='replace',index=False)

9993

In [77]:
verify= pd.read_sql("select count(*)as total_number from orders", engine)
print(verify)

   total_number
0          9993

In [78]:
import anthropic
import pandas as pd
from sqlalchemy import create_engine

# Paste your API key here
client = anthropic.Anthropic(api_key="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")

engine = create_engine('sqlite:///retail.db')

def ask_data(question):
    # Step 1: AI converts question to SQL
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=500,
        messages=[{
            "role": "user",
            "content": f"""You are a SQL expert working with a retail orders database.
            
Table name: orders
Columns: order_id, order_date, ship_mode, segment, country, city, 
         state, postal_code, region, category, sub_category,
         cost_price, list_price, quantity, discount_percent,
         order_month, order_year, order_quarter,
         discount, sale_price, profit, revenue, profit_margin

Convert this question to a valid SQLite query:
Question: {question}

Return ONLY the SQL query, nothing else. No explanation, no markdown."""
        }]
    )
    
    sql = response.content[0].text.strip()
    
    # Step 2: Run SQL against database
    try:
        results = pd.read_sql(sql, engine)
        
        # Step 3: AI explains results in plain English
        explanation = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=300,
            messages=[{
                "role": "user",
                "content": f"""Question: {question}
SQL Results: {results.to_string()}
Explain the answer in 2-3 clear sentences for a business user."""
            }]
        )
        
        return sql, results, explanation.content[0].text
        
    except Exception as e:
        return sql, None, f"Error running query: {str(e)}"

print("✅ AI Agent ready!")

✅ AI Agent ready!

In [82]:
from groq import Groq
import pandas as pd
from sqlalchemy import create_engine

# Paste your Groq API key here
client = Groq(api_key="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")

engine = create_engine('sqlite:///retail.db')

def ask_data(question):
    # Step 1: AI converts question to SQL
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{
            "role": "user",
            "content": f"""You are a SQL expert working with a retail orders database.
            
Table name: orders
Columns: order_id, order_date, ship_mode, segment, country, city, 
         state, postal_code, region, category, sub_category,
         cost_price, list_price, quantity, discount_percent,
         order_month, order_year, order_quarter,
         discount, sale_price, profit, revenue, profit_margin

Convert this question to a valid SQLite query:
Question: {question}

Return ONLY the SQL query, nothing else. No explanation, no markdown."""
        }],
        max_tokens=500
    )
    
    sql = response.choices[0].message.content.strip()
    
    # Step 2: Run SQL against database
    try:
        results = pd.read_sql(sql, engine)
        
        # Step 3: AI explains results in plain English
        explanation = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{
                "role": "user",
                "content": f"""Question: {question}
SQL Results: {results.to_string()}
Explain the answer in 2-3 clear sentences for a business user."""
            }],
            max_tokens=300
        )
        
        return sql, results, explanation.choices[0].message.content
        
    except Exception as e:
        return sql, None, f"Error running query: {str(e)}"

print("✅ AI Agent ready!")

✅ AI Agent ready!

In [83]:
# Test 1 - Simple question
question = "What are the top 5 regions by total revenue?"
sql, results, answer = ask_data(question)

print("❓ Question:", question)
print("\n📝 SQL Generated:")
print(sql)
print("\n📊 Results:")
print(results)
print("\n🤖 AI Answer:")
print(answer)

❓ Question: What are the top 5 regions by total revenue?

📝 SQL Generated:
SELECT region, SUM(revenue) as total_revenue FROM orders GROUP BY region ORDER BY total_revenue DESC LIMIT 5

📊 Results:
    region  total_revenue
0     West      3467409.6
1     East      3257983.8
2  Central      2387881.2
3    South      1965901.6

🤖 AI Answer:
The top 5 regions by total revenue are led by the West region, which generated approximately $3.47 million in revenue. The East region follows closely with around $3.26 million, while the Central and South regions trail behind with $2.39 million and $1.97 million, respectively. Note that there are only four regions listed, so they are the top 4 regions by total revenue, rather than the top 5.

In [84]:
questions = [
    "What is the most profitable product category?",
    "Which month had the highest total revenue?",
    "What is the average profit margin by segment?"
]

for q in questions:
    print("=" * 60)
    sql, results, answer = ask_data(q)
    print(f"❓ {q}")
    print(f"\n📝 SQL: {sql}")
    print(f"\n📊 Results:\n{results}")
    print(f"\n🤖 {answer}\n")

============================================================
❓ What is the most profitable product category?

📝 SQL: SELECT category FROM orders GROUP BY category ORDER BY SUM(profit) DESC LIMIT 1

📊 Results:
     category
0  Technology

🤖 The most profitable product category is Technology, as indicated by the SQL results. This suggests that businesses can generate significant revenue by investing in technology-related products, such as software, hardware, or gadgets. By focusing on the technology sector, companies can tap into a lucrative market with high demand and potential for substantial returns.

============================================================
❓ Which month had the highest total revenue?

📝 SQL: SELECT order_month FROM orders GROUP BY order_month ORDER BY SUM(revenue) DESC LIMIT 1

📊 Results:
   order_month
0           10

🤖 The month with the highest total revenue is October, as indicated by the order_month value of 10. This suggests that the business generated the most revenue during October, which could be due to various factors such as seasonal demand or promotional activities. By identifying the peak revenue month, the business can plan and optimize its strategies to maximize sales and revenue during this period.

============================================================
❓ What is the average profit margin by segment?

📝 SQL: SELECT segment, AVG(profit_margin) AS average_profit_margin FROM orders GROUP BY segment

📊 Results:
       segment  average_profit_margin
0     Consumer               5.351504
1    Corporate               5.261486
2  Home Office               5.233146

🤖 The average profit margin varies by segment, with the Consumer segment having the highest average profit margin of 5.35%. The Corporate and Home Office segments have slightly lower average profit margins, at 5.26% and 5.23% respectively. This indicates that the company generates the most profit per dollar of sales from its Consumer segment, followed closely by its Corporate and Home Office segments.

In [85]:
import os
print(os.getcwd())

C:\Users\Sam